apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:OtoAnalytics/infra-manifests
      name: infra-manifests
      sshPrivateKeySecret:
        name: argocd-github
        key: sshPrivateKey
    - url: https://github.com/eytanhanig/argoproj-deployments
      name: argoproj-deployments
    - url: https://github.com/argoproj/argocd-example-apps.git
      name: example-apps
    - type: helm
      url: https://kubernetes-charts.storage.googleapis.com
      name: stable
    - type: helm
      url: https://argoproj.github.io/argo-helm
      name: argo

  # Enables application status badge feature
  statusbadge.enabled: 'true'

  # Enables anonymous user access. The anonymous users get default role permissions specified argocd-rbac-cm.yaml.
  users.anonymous.enabled: "false"
