apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  source:
    path: sealed-secrets
    repoURL: https://github.com/eytanhanig/argoproj-deployments.git
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default
