apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eytanhanig/argoproj-deployments
    path: sealed-secrets
    # targetRevision: HEAD
    targetRevision: master
    # helm:
    #   releaseName: myRelease
    #   valueFiles:
    #     - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  info:
    - name: test
      value: ''

    # componentParameterOverrides:
    # - name: cluster.name
    #   value: my-elasticsearch