apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# This references the OSS https://github.com/kbst/catalog/tree/sealed-secrets-v0.9.7-kbst.0/src/sealed-secrets/base
- github.com/kbst/catalog//src/sealed-secrets/base?ref=sealed-secrets-v0.9.7-kbst.0
