apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: default
spec:
  encryptedData:
    admin.password: AgDE77N4uZ11fD7gwtAkEXTvQU1vDps5fGphPg5c5j99guTjXDdDWFVZYw7gQRdalFDKSJHRTXuY3D4Lpe5VFsAPYFgcAnI8cWDywqtYSdQnAo9Ufkrtla8NyCdpkKAIhjalAYcDxe7QhRKnbTgRExSyd3NQF8mGT0Oh/bOGMBQjlrC2A5AjxXjI/I89esKBhSGakGeQsgaVoynaWpXTh0UgkoO3hFySGaS8seygskvkClqBMzBxiZNGn32IVOt7RltRAJVYYOm0Pd5abXCwt0QQ0udcS8f3obystCzohYQE9E5X70O3PqngvQHXI5PvWMMB6BUcJzsk+gbai7zoeMdZ8nKZc/PxPEhZFfif2KAI7VYGcBKZHSXlpCjl/oi9Q53czYRseR9nfo3tzsjUYoFzYmwDHqWSN9wd/VS6TKgJAlgp0wUfS54z7kAljGbtaDObDUj+8QuIrZUEaAjj1FJpRibPpFNXaJb+n99OFZYaFMlK8U09xui+Msb7W4E7zCtRuo15ipfgoAMgAIX4GTg+b1fgIaAiejRKJCmxyFNBNuECONfXI5DS+kIeDVufHnp24MblRrxxR4nHNph1O5monXd23xFd6I6MHvjP729tlsHj/dhZ4OVJzg9kGTdnEW9xZNHHHRfxYJU5yYZMYCQz7Yzj0hsS8s62WRgeCz64kfqWVWV7+mPQsrJKaH03Qq8Cxy55EqGZOQSKq13YHNj1ueSOgLkbezadFd0wLi/HeQwfiII6J6hF4HlFd02UPU8AdNBiHQPhZxzo8is=
    sshPrivateKey: AgArIemEoA8x6f3CsoyxKtH8De5/DIgoSogBtMjpvAW0uu153y5ruL0m4eiCkuk1llljsdq4dLvMZFEnV6qbnpJ/+KOftvmsX+97orfduqXnQVjTepOzaT98hoChgXTy4eQcqtGRodnKZbVsBCu9wvMNDPVhIv45Lr1QkFgyV40tMKcW7KCmEJIIKI7e6N/povHDRo67SNywF5MI8UHx9311x+oE+KiqV9LTuj4ePqf25Ai3K9vrV83/FFzgTfXxxFPmDbLJR9oJKKMs3CB10hVjCDy0VQV2BbnntebHaYVq/2bFTK+m8Z+IbNFHi1FyQwf5m23QRLoY0zoZmEe+wkhBjiDxIDMZKkiBlXMNpFFygS8rGA0kfVyQzV7U9jMLT/NifRQr1kY8+mEPJRf3njzllPhKKpE7fd/ja34sQHWMj2UhRstacllHXKHmRxxyxtqQadT0f0luFeUdZBr1ts+LL+k6KSdhTj+gOVTYmTZeglYJ50zR7EWeMZyp6Dk5haLnr9Fx56W6qKo+8hzN9Y3Act5n4K0Qc1nn+BsfsgHRrXHCVibndYHbwPccA4qNkKVLAqmXKnjqXJ3wedQzDDlkyHiOQcr3sXypBjyQs+y2A5fzRAYaLZcoZY7dajtbpSHbpOiacKRCedB4tikA6ZwqU0/xwdAM7hUGwDLDC/P1jLW+mTgG4NgmhnqmY/pIbi/oJV0d8vAoa6tGupYY3G+2zOT6RFnYn8K3X630UJI5n/AoxP8HaOHTejl/Dyl/LCDJISkRq4AtwNzPc73lQsyIi2Sa6x11DOoPoAkcjj7Pg4f0KN5Sttp+o/ze5W6iP/tNZAKZtgJ9vOMTek7MVIAue7bq1c58Q7JZycX0lVMYvJYwynumqs7dC5+lf+sNc0Xno0ISqxb0akq21qv6JgKA4NEdqt/3ZBcvN7G8t9tLTcWBWokrqirrdTAaP4sce6FfLdhG5bLhK4ft8runWNxImW+aj3N3hhhVQ3oq5aL/lkYBTmjLeOUvf7++z76/EKxOqdiSU06BD0EOxyKrTFzs7O2HcT6eKVNKYTMm0sSHRkBe4b1y4BxDDjd8lPT8tMX5w/hjg1RPgGcGplq9bnpqEHXf3y3YwQojerKqtCq2QAu7Y3pAeJJRdR4Ul7XL3gtlKOCghajJY3uqUGCg+975k72F2CgPVQU43qkG4vTP+trKOQhIQJVJZ5379g4KHCV7DUFqqr/4/6aCLnUIJOs=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: default
    type: Opaque
status: {}

