apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-ui-cert
spec:
  secretName: argo-ui-tls
  issuerRef:
    name: argo-ci-issuer
    kind: Issuer
  commonName: ci.apps.argoproj.io
  dnsNames:
  - ci.apps.argoproj.io
