apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgBmd43W3Pn7oo5aAT7HFDBrkGeoyya5AuJ8uJTq14nYnIleBqrLC4g1X5oLvRyEwzFuhT5l2ICb6MD9WmbJ27//LZNK8KOltpB9Gje+ReiVnEQXHxoafVilsjimKWtlqRJivkMkVegeBYQ2oC7dzJy9d5NMnqt29AJzEM/K0+oQ/HbKXvX56zP8L13szPjvUCql9GcnzXy/x6m2I9xMBID/3q/Sw81baPL7kZ8ZOxkfDCLPyvxCyCiBap/chEMfp70M8bBfcL3GmSAE9yXMgSDaHP3faL8f9YjG3Qn2dw8gZmzyar52RN+UHVB4vCsIQw4XzwA5GTzyVD1GxsG81MlC36Ub6JrBR0eQqAnmup2rhyfURCHAXSa79NN0kHw4L9iA3LoZFNtNHS2TTEgxJ6ckmF+gU1yMjnJYV6h6a5rBiEK/1oxx0NFRm4Rgb7/PyKOMIOOztCtXEhLjaHWxyLWTbebQNWQBT1HPVzsxncRPSbMPnd2aRNUXg5NpRSoN09gGrpkfajHTGbF1B425S0ryzwgVgcqWsNqQnUOCetoVPswuEulnqkRHI6grtIJ2yj0uo8txs93JLmLoDZdXvGouGeOFY9QjmTi2pOcWGgKVfFlSaa+l4TmkYXpVg4tjc8i7luOI5pT43CAwGQftKI+nrlzlbKShejDcWYwXvaDbP2XDY+Pq5Cv/Ha1CiVn7WKHvhf/ISd9E6wzNARzGxUyFhzA2SrT95x1Ml4IPykbYZw==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog
status: {}
