apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argocd-namespace.yaml
- overlays/common/sealed-argocd-github-secret.yaml
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-1.4
# - github.com/argoproj-labs/argocd-notifications//manifests/base?ref=release-0.3

patchesStrategicMerge:
- overlays/common/argocd-secret.yaml
- overlays/common/argocd-cm.yaml
# - overlays/common/argocd-sealedsecret.yaml
# - overlays/common/argocd-server-service.yaml
# - overlays/common/argocd-server-deploy.yaml
# - overlays/common/argocd-repo-server-deploy.yaml
# - overlays/common/argocd-notifications-cm.yaml

namespace: argocd

# images:
# - name: argoproj/argocd
#   ###--- https://hub.docker.com/r/argoproj/argocd/tags
#   newName: argoproj/argocd
#   # newTag: v1.4.0
#   newTag: v1.4.2
#   # newTag: v1.4.2
# # - name: argoprojlabs/argocd-notifications
# #   ###--- Ref: https://hub.docker.com/r/argoprojlabs/argocd-notifications/tags
# #   newName: argoprojlabs/argocd-notifications
# #   newTag: v0.4.0
# #   # newTag: v0.4.1
# #   # newTag: v0.4.2
