apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argocd-namespace.yaml
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-1.4
- base/sealed-argocd-github-secret.yaml

patchesStrategicMerge:
- overlays/argocd-cm.yaml

namespace: argocd
