apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - base/argo-cd-issuer.yaml
# - base/argo-cd-certificate.yaml
# - base/http01-ingress.yaml
# - base/argo-cd-ui-ingress.yaml
# # - base/argo-cd-secret.yaml
# # - base/jenkins-ingress.yaml
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-1.4
# - github.com/argoproj-labs/argocd-notifications//manifests/base?ref=release-0.3

patchesStrategicMerge:
- overlays/common/argo-cd-cm.yaml
- overlays/common/argo-cd-argocd-secret.yaml
# - overlays/common/argocd-server-service.yaml
# - overlays/common/argocd-server-deploy.yaml
# - overlays/common/argocd-repo-server-deploy.yaml
# - overlays/common/argocd-notifications-cm.yaml

namespace: argocd

images:
- name: argoproj/argocd
  ###--- https://hub.docker.com/r/argoproj/argocd/tags
  newName: argoproj/argocd
  # newTag: v1.4.0
  newTag: v1.4.1
  # newTag: v1.4.2
# - name: argoprojlabs/argocd-notifications
#   ###--- Ref: https://hub.docker.com/r/argoprojlabs/argocd-notifications/tags
#   newName: argoprojlabs/argocd-notifications
#   newTag: v0.4.0
#   # newTag: v0.4.1
#   # newTag: v0.4.2
