datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  logsEnabled: true
  logsConfigContainerCollectAll: true
  nonLocalTraffic: true
  processAgentEnabled: true
  logLevel: ERROR
