apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoci
spec:
  destination:
    namespace: argoci
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoci
    repoURL: https://github.com/eytanhanig/argoproj-deployments
    targetRevision: HEAD
