apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eytanhanig/argoproj-deployments'
    path: sealed-secrets
    targetRevision: eytan
    # helm:
    #   releaseName: myRelease
    #   valueFiles:
    #     - values.yaml
    # kustomize:
    #   patchesStrategicMerge:
    #   - overlays/common/argocd-cm.yaml
    #   - overlays/common/argocd-secret.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    # componentParameterOverrides:
    # - name: cluster.name
    #   value: my-elasticsearch